const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Physics,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Gritsenko_Spine,
		C3.Plugins.Browser,
		C3.Behaviors.scrollto,
		C3.Plugins.List,
		C3.Plugins.Touch,
		C3.Plugins.sliderbar,
		C3.Plugins.MixonGames_EasySiteLock,
		C3.Behaviors.Tween,
		C3.Plugins.AJAX,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Behaviors.Rotate,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.skymenTrail,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Gritsenko_Spine.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Gritsenko_Spine.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Gritsenko_Spine.Acts.ZMoveToObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Gritsenko_Spine.Cnds.PickByUID,
		C3.Plugins.Gritsenko_Spine.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Gritsenko_Spine.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Gritsenko_Spine.Cnds.PickParent,
		C3.Plugins.Gritsenko_Spine.Acts.SetEffectParam,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Particles.Acts.SetEffectParam,
		C3.Plugins.Gritsenko_Spine.Cnds.IsAnimationPlaying,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimation,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Gritsenko_Spine.Cnds.OnAnimationFinished,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Gritsenko_Spine.Cnds.OnCreated,
		C3.Plugins.Gritsenko_Spine.Exps.X,
		C3.Plugins.Gritsenko_Spine.Exps.Y,
		C3.Plugins.Gritsenko_Spine.Acts.AddChild,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Gritsenko_Spine.Cnds.OnSkeletonLoaded,
		C3.Plugins.Gritsenko_Spine.Acts.SetSize,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Gritsenko_Spine.Acts.Flip,
		C3.Plugins.Gritsenko_Spine.Acts.SetBoolInstanceVar,
		C3.Plugins.Gritsenko_Spine.Cnds.CompareX,
		C3.Plugins.Gritsenko_Spine.Cnds.OnEvent,
		C3.Plugins.Gritsenko_Spine.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Gritsenko_Spine.Cnds.IsSkeletonLoaded,
		C3.Plugins.Gritsenko_Spine.Acts.UpdateBBoxes,
		C3.Plugins.Gritsenko_Spine.Exps.SpineBBoxCenterX,
		C3.Plugins.Gritsenko_Spine.Exps.SpineBBoxCenterY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Gritsenko_Spine.Exps.Animations,
		C3.Plugins.Gritsenko_Spine.Exps.Skins,
		C3.Plugins.Gritsenko_Spine.Acts.CreateCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.AddCustomSkin,
		C3.Plugins.Gritsenko_Spine.Acts.SetCustomSkin,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Gritsenko_Spine.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Gritsenko_Spine.Exps.UID,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Gritsenko_Spine.Acts.DeleteAnimation,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimationSpeed,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Gritsenko_Spine.Acts.SetSkin,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Gritsenko_Spine.Acts.AddInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Browser.Cnds.WindowHasFocus,
		C3.Plugins.Browser.Acts.Focus,
		C3.Plugins.List.Acts.SetInstanceVar,
		C3.Plugins.sliderbar.Acts.SetInstanceVar,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Gritsenko_Spine.Exps.TextureWidth,
		C3.Plugins.Gritsenko_Spine.Exps.TextureHeight,
		C3.Plugins.MixonGames_EasySiteLock.Acts.CheckDomain,
		C3.Plugins.MixonGames_EasySiteLock.Cnds.OnChecked,
		C3.Plugins.MixonGames_EasySiteLock.Cnds.IsLocked
	];
};
self.C3_JsPropNameTable = [
	{selfY: 0},
	{"8Direction": 0},
	{Physics: 0},
	{OBJ_PlayerRange: 0},
	{Array_2letter: 0},
	{ID: 0},
	{OBJ_EnemyMovement1: 0},
	{lastX: 0},
	{lastY: 0},
	{UI_TypeAnswer: 0},
	{TXT_Answer: 0},
	{OBJ_EnemyMovement2: 0},
	{AdvancedRandom: 0},
	{TB_Grass: 0},
	{Keyboard: 0},
	{OBJ_EnemyMovement3: 0},
	{OBJ_EnemyMovement4: 0},
	{Flip: 0},
	{wordPick: 0},
	{word: 0},
	{letter1: 0},
	{letter2: 0},
	{letter3: 0},
	{letter4: 0},
	{letter5: 0},
	{letter6: 0},
	{letter7: 0},
	{hp: 0},
	{OBJ_EnemySpine1: 0},
	{Browser: 0},
	{flip: 0},
	{attackLeft: 0},
	{weapon: 0},
	{HP: 0},
	{OBJ_PlayerSpine: 0},
	{ScrollTo: 0},
	{OBJ_Cam: 0},
	{OBJ_EnemySpine2: 0},
	{List_PlayerAnimation: 0},
	{List_EnemyAnimation: 0},
	{Touch: 0},
	{slideBar_PlayerAnimationSpeed: 0},
	{slideBar_EnemyAnimationSpeed: 0},
	{TXT_SlidebarPlayer: 0},
	{TXT_SlidebarEnemy: 0},
	{List_PlayerSkin: 0},
	{OBJ_EnemySpine3: 0},
	{OBJ_EnemySpine4: 0},
	{OBJ_CenterPlayer: 0},
	{EasySiteLock: 0},
	{OBJ_AttackWizard: 0},
	{OBJ_SpawnerAttackPlayerR: 0},
	{OBJ_ChironRangeAttack: 0},
	{OBJ_SpawnerAttackEnemyR: 0},
	{OBJ_NuWaRangeAttack: 0},
	{UI_Heart: 0},
	{TXT_Wave: 0},
	{Tween: 0},
	{TXT_Score: 0},
	{OBJ_SpawnerAttackEnemyL: 0},
	{OBJ_AngleEnemyRangeR: 0},
	{OBJ_AngleEnemyRangeL: 0},
	{OBJ_EnemySpine5: 0},
	{AJAX: 0},
	{target: 0},
	{TB_Answer: 0},
	{OBJ_BossRangeAttack: 0},
	{Array_3letter: 0},
	{Array_4letter: 0},
	{Array_5letter: 0},
	{Array_CurrentWord: 0},
	{Array_6letter: 0},
	{UI_Skill1: 0},
	{UI_Skill2: 0},
	{UI_Skill3: 0},
	{OBJ_EnemyMovement5: 0},
	{UI_Board: 0},
	{hirarki_board: 0},
	{BTN_Close: 0},
	{TXT_Mode: 0},
	{TXT_Static: 0},
	{OBJ_AnglePlayerRangeR: 0},
	{OBJ_AnglePlayerRangeL: 0},
	{OBJ_SpawnerAttackPlayerL: 0},
	{Array_7letter: 0},
	{Bullet: 0},
	{OBJ_SkillFire: 0},
	{Fade: 0},
	{OBJ_SkillFireImpact: 0},
	{OBJ_SkillIce: 0},
	{OBJ_SkillThunder: 0},
	{OBJ_EnemyCollision: 0},
	{Solid: 0},
	{ENV_PropertySolid: 0},
	{OBJ_PlayerCollision: 0},
	{Timer: 0},
	{OBJ_SkillOrb: 0},
	{OBJ_WeaponWizard: 0},
	{UI_Space: 0},
	{OBJ_PlayerMovement: 0},
	{ENV_Property: 0},
	{TB_Grass2: 0},
	{OBJ_Solid: 0},
	{BTN_Restart: 0},
	{BTN_Home: 0},
	{TXT_HighScore: 0},
	{TXT_ScoreResult: 0},
	{BTN_Pause: 0},
	{UI_HirarkiTL: 0},
	{UI_HirarkiTR: 0},
	{UI_HirarkiBR: 0},
	{UI_HirarkiBL: 0},
	{BG_Black: 0},
	{Audio: 0},
	{OBJ_EnemyDirection: 0},
	{OBJ_EnemyAttackArea: 0},
	{LocalStorage: 0},
	{Dictionary: 0},
	{UI_playerVFX: 0},
	{Rotate: 0},
	{loading: 0},
	{BTN_Audio: 0},
	{BG_Menu: 0},
	{BG_Sky: 0},
	{BG_Sea: 0},
	{OBJ_Awan: 0},
	{UI_Title: 0},
	{BTN_Play: 0},
	{Mouse: 0},
	{OBJ_HirarkiBoard: 0},
	{UI_ModeSelect: 0},
	{BTN_Easy: 0},
	{BTN_Medium: 0},
	{BTN_Hard: 0},
	{TB_Chain: 0},
	{UI_ModeSelect2: 0},
	{hero: 0},
	{BTN_Hero: 0},
	{BTN_Back: 0},
	{OBJ_TransitionLeft: 0},
	{OBJ_TransitionRight: 0},
	{Sine: 0},
	{OBJ_Light: 0},
	{OBJ_Sun: 0},
	{UI_playerVFX2: 0},
	{VFX_lightCrystal: 0},
	{InstanceName: 0},
	{Progress: 0},
	{LoadingScreenDummy: 0},
	{ProgressBg: 0},
	{ProgressBarFg: 0},
	{ProgressBarBg: 0},
	{VFX_WizardAttack1: 0},
	{VFX_WizardAttack2: 0},
	{VFX_WizardAttack3: 0},
	{TrailRenderer: 0},
	{Trail: 0},
	{VFX_lightWizardOrb: 0},
	{VFX_StaffWizard: 0},
	{UI_Keyboard: 0},
	{TXT_CheckEnemyOnScreen: 0},
	{TXT_Version: 0},
	{Family_EnemyMovement: 0},
	{Family_zOrder1: 0},
	{Family_zOrder2: 0},
	{Family_Spine: 0},
	{Flash: 0},
	{Family_SpineEnemy: 0},
	{MoveTo: 0},
	{Family_AttackBullet: 0},
	{Family_AttackEnemy: 0},
	{Family_Button: 0},
	{Family_Vfx: 0},
	{Family_DropItem: 0},
	{Family_UISkill: 0},
	{mode: 0},
	{score: 0},
	{highScoreEasy: 0},
	{highScoreMedium: 0},
	{highScoreHard: 0},
	{targetAnswerFull: 0},
	{targetAnswerUID: 0},
	{targetInput: 0},
	{targetCurrent: 0},
	{targetCurrentIndex: 0},
	{targetAnswer1: 0},
	{targetAnswer2: 0},
	{targetAnswer3: 0},
	{targetAnswer4: 0},
	{targetAnswer5: 0},
	{targetAnswer6: 0},
	{targetAnswer7: 0},
	{Skill1: 0},
	{Skill2: 0},
	{Skill3: 0},
	{pause: 0},
	{audio: 0},
	{position: 0},
	{enemy: 0},
	{text: 0},
	{randomSpawnEnemy: 0},
	{wave: 0},
	{EnemySpawn: 0},
	{EnemyLeft: 0},
	{bosSpawnStatic: 0},
	{maxEnemy: 0},
	{maxSpeedEnemy: 0},
	{minSpeedEnemy: 0},
	{force: 0},
	{skillActive: 0},
	{type: 0},
	{modeLenght: 0},
	{loadingCurrent: 0},
	{loadingMax: 0},
	{fade: 0},
	{layout: 0},
	{buttonActive: 0},
	{currentMenu: 0}
];

self.InstanceType = {
	OBJ_PlayerRange: class extends self.ISpriteInstance {},
	Array_2letter: class extends self.IArrayInstance {},
	OBJ_EnemyMovement1: class extends self.ISpriteInstance {},
	UI_TypeAnswer: class extends self.ISpriteInstance {},
	TXT_Answer: class extends self.ITextInstance {},
	OBJ_EnemyMovement2: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	TB_Grass: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	OBJ_EnemyMovement3: class extends self.ISpriteInstance {},
	OBJ_EnemyMovement4: class extends self.ISpriteInstance {},
	OBJ_EnemySpine1: class extends self.IWorldInstance {},
	Browser: class extends self.IInstance {},
	OBJ_PlayerSpine: class extends self.IWorldInstance {},
	OBJ_Cam: class extends self.ISpriteInstance {},
	OBJ_EnemySpine2: class extends self.IWorldInstance {},
	List_PlayerAnimation: class extends self.IListInstance {},
	List_EnemyAnimation: class extends self.IListInstance {},
	Touch: class extends self.IInstance {},
	slideBar_PlayerAnimationSpeed: class extends self.ISliderBarInstance {},
	slideBar_EnemyAnimationSpeed: class extends self.ISliderBarInstance {},
	TXT_SlidebarPlayer: class extends self.ITextInstance {},
	TXT_SlidebarEnemy: class extends self.ITextInstance {},
	List_PlayerSkin: class extends self.IListInstance {},
	OBJ_EnemySpine3: class extends self.IWorldInstance {},
	OBJ_EnemySpine4: class extends self.IWorldInstance {},
	OBJ_CenterPlayer: class extends self.ISpriteInstance {},
	EasySiteLock: class extends self.C3.Plugins.MixonGames_EasySiteLock.Instance {},
	OBJ_AttackWizard: class extends self.ISpriteInstance {},
	OBJ_SpawnerAttackPlayerR: class extends self.ISpriteInstance {},
	OBJ_ChironRangeAttack: class extends self.ISpriteInstance {},
	OBJ_SpawnerAttackEnemyR: class extends self.ISpriteInstance {},
	OBJ_NuWaRangeAttack: class extends self.ISpriteInstance {},
	UI_Heart: class extends self.ISpriteInstance {},
	TXT_Wave: class extends self.ITextInstance {},
	TXT_Score: class extends self.ITextInstance {},
	OBJ_SpawnerAttackEnemyL: class extends self.ISpriteInstance {},
	OBJ_AngleEnemyRangeR: class extends self.ISpriteInstance {},
	OBJ_AngleEnemyRangeL: class extends self.ISpriteInstance {},
	OBJ_EnemySpine5: class extends self.IWorldInstance {},
	AJAX: class extends self.IInstance {},
	TB_Answer: class extends self.ITiledBackgroundInstance {},
	OBJ_BossRangeAttack: class extends self.ISpriteInstance {},
	Array_3letter: class extends self.IArrayInstance {},
	Array_4letter: class extends self.IArrayInstance {},
	Array_5letter: class extends self.IArrayInstance {},
	Array_CurrentWord: class extends self.IArrayInstance {},
	Array_6letter: class extends self.IArrayInstance {},
	UI_Skill1: class extends self.ISpriteInstance {},
	UI_Skill2: class extends self.ISpriteInstance {},
	UI_Skill3: class extends self.ISpriteInstance {},
	OBJ_EnemyMovement5: class extends self.ISpriteInstance {},
	UI_Board: class extends self.ISpriteInstance {},
	hirarki_board: class extends self.ISpriteInstance {},
	BTN_Close: class extends self.ISpriteInstance {},
	TXT_Mode: class extends self.ITextInstance {},
	TXT_Static: class extends self.ITextInstance {},
	OBJ_AnglePlayerRangeR: class extends self.ISpriteInstance {},
	OBJ_AnglePlayerRangeL: class extends self.ISpriteInstance {},
	OBJ_SpawnerAttackPlayerL: class extends self.ISpriteInstance {},
	Array_7letter: class extends self.IArrayInstance {},
	OBJ_SkillFire: class extends self.ISpriteInstance {},
	OBJ_SkillFireImpact: class extends self.ISpriteInstance {},
	OBJ_SkillIce: class extends self.ISpriteInstance {},
	OBJ_SkillThunder: class extends self.ISpriteInstance {},
	OBJ_EnemyCollision: class extends self.ISpriteInstance {},
	ENV_PropertySolid: class extends self.ISpriteInstance {},
	OBJ_PlayerCollision: class extends self.ISpriteInstance {},
	OBJ_SkillOrb: class extends self.ISpriteInstance {},
	OBJ_WeaponWizard: class extends self.ISpriteInstance {},
	UI_Space: class extends self.ISpriteInstance {},
	OBJ_PlayerMovement: class extends self.ISpriteInstance {},
	ENV_Property: class extends self.ISpriteInstance {},
	TB_Grass2: class extends self.ITiledBackgroundInstance {},
	OBJ_Solid: class extends self.ISpriteInstance {},
	BTN_Restart: class extends self.ISpriteInstance {},
	BTN_Home: class extends self.ISpriteInstance {},
	TXT_HighScore: class extends self.ITextInstance {},
	TXT_ScoreResult: class extends self.ITextInstance {},
	BTN_Pause: class extends self.ISpriteInstance {},
	UI_HirarkiTL: class extends self.ISpriteInstance {},
	UI_HirarkiTR: class extends self.ISpriteInstance {},
	UI_HirarkiBR: class extends self.ISpriteInstance {},
	UI_HirarkiBL: class extends self.ISpriteInstance {},
	BG_Black: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	OBJ_EnemyDirection: class extends self.ISpriteInstance {},
	OBJ_EnemyAttackArea: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	UI_playerVFX: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	BTN_Audio: class extends self.ISpriteInstance {},
	BG_Menu: class extends self.ISpriteInstance {},
	BG_Sky: class extends self.ISpriteInstance {},
	BG_Sea: class extends self.ISpriteInstance {},
	OBJ_Awan: class extends self.ISpriteInstance {},
	UI_Title: class extends self.ISpriteInstance {},
	BTN_Play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	OBJ_HirarkiBoard: class extends self.ISpriteInstance {},
	UI_ModeSelect: class extends self.ISpriteInstance {},
	BTN_Easy: class extends self.ISpriteInstance {},
	BTN_Medium: class extends self.ISpriteInstance {},
	BTN_Hard: class extends self.ISpriteInstance {},
	TB_Chain: class extends self.ITiledBackgroundInstance {},
	UI_ModeSelect2: class extends self.ISpriteInstance {},
	BTN_Hero: class extends self.ISpriteInstance {},
	BTN_Back: class extends self.ISpriteInstance {},
	OBJ_TransitionLeft: class extends self.ISpriteInstance {},
	OBJ_TransitionRight: class extends self.ISpriteInstance {},
	OBJ_Light: class extends self.ISpriteInstance {},
	OBJ_Sun: class extends self.ISpriteInstance {},
	UI_playerVFX2: class extends self.ISpriteInstance {},
	VFX_lightCrystal: class extends self.ISpriteInstance {},
	Progress: class extends self.ITextInstance {},
	LoadingScreenDummy: class extends self.ISpriteInstance {},
	ProgressBg: class extends self.ISpriteInstance {},
	ProgressBarFg: class extends self.ISpriteInstance {},
	ProgressBarBg: class extends self.ISpriteInstance {},
	VFX_WizardAttack1: class extends self.IParticlesInstance {},
	VFX_WizardAttack2: class extends self.IParticlesInstance {},
	VFX_WizardAttack3: class extends self.IParticlesInstance {},
	Trail: class extends self.ISpriteInstance {},
	VFX_lightWizardOrb: class extends self.ISpriteInstance {},
	VFX_StaffWizard: class extends self.IParticlesInstance {},
	UI_Keyboard: class extends self.ISpriteInstance {},
	TXT_CheckEnemyOnScreen: class extends self.ITextInstance {},
	TXT_Version: class extends self.ITextInstance {},
	Family_EnemyMovement: class extends self.ISpriteInstance {},
	Family_zOrder1: class extends self.ISpriteInstance {},
	Family_zOrder2: class extends self.ISpriteInstance {},
	Family_Spine: class extends self.IWorldInstance {},
	Family_SpineEnemy: class extends self.IWorldInstance {},
	Family_AttackBullet: class extends self.ISpriteInstance {},
	Family_AttackEnemy: class extends self.ISpriteInstance {},
	Family_Button: class extends self.ISpriteInstance {},
	Family_Vfx: class extends self.IParticlesInstance {},
	Family_DropItem: class extends self.ISpriteInstance {},
	Family_UISkill: class extends self.ISpriteInstance {}
}